create table departments (dept_id int not null, dept_name char(20), primary key(dept_id));
create table employees (emp_id int not null, emp_name char(20), dept_id int, salary int, primary key(emp_id), foreign key(dept_id) references departments(dept_id));
insert into departments values(1, 'Engineering');
insert into departments values(2, 'Sales');
insert into employees values(1, 'Alice', 1, 100000);
insert into employees values(2, 'Bob', 2, 80000);
insert into employees values(3, 'Charlie', 1, 120000);
create index emp_dept_idx on employees(dept_id);
select e.emp_name, d.dept_name from employees e, departments d where e.dept_id = d.dept_id and e.dept_id = 1;
begin;
update employees set salary = 130000 where emp_id = 3;
select * from employees where emp_id = 3;
rollback;
select * from employees where emp_id = 3;
update employees set dept_id = 2 where emp_id = 1;
select * from employees where emp_id = 1;
update employees set dept_id = 99 where emp_id = 1;
begin;
delete from employees where emp_id = 1;
rollback;
select * from employees;
drop table employees;
drop table departments;
exit;
