create table test_index (id int not null, name char(20), age int, primary key(id));
insert into test_index values(1, 'alice', 25);
insert into test_index values(2, 'bob', 30);
insert into test_index values(3, 'charlie', 35);
insert into test_index values(4, 'dave', 40);
create index idx_id on test_index(id);
select * from test_index where id = 2;
explain test_index;
insert into test_index values(5, 'eve', 28);
select * from test_index where id = 5;
delete from test_index where id = 2;
select * from test_index where id = 2;
update test_index set id = 99 where id = 1;
select * from test_index where id = 99;
create index bad_idx on nonexistent(id);
create index bad_col on test_index(nonexistent);
drop index test_index.id;
select * from test_index where id = 3;
drop table test_index;
exit;
