create table test_tx (id int not null, name char(20), balance int, primary key(id));
insert into test_tx values(1, 'alice', 1000);
insert into test_tx values(2, 'bob', 500);
begin;
insert into test_tx values(3, 'charlie', 750);
select * from test_tx;
rollback;
select * from test_tx;
begin;
insert into test_tx values(3, 'charlie', 750);
commit;
select * from test_tx;
update test_tx set name = 'modified' where id = 1;
begin;
update test_tx set name = 'in_tx' where id = 1;
select * from test_tx where id = 1;
rollback;
select * from test_tx where id = 1;
begin;
delete from test_tx where id = 2;
select * from test_tx;
rollback;
select * from test_tx;
begin;
insert into test_tx values(4, 'dave', 300);
update test_tx set balance = 2000 where id = 1;
delete from test_tx where id = 3;
select * from test_tx;
rollback;
select * from test_tx;
begin;
update test_tx set balance = 1500 where id = 1;
insert into test_tx values(4, 'dave', 300);
commit;
select * from test_tx;
drop table test_tx;
exit;
